experiment_name: lr_scheduling_cosine_annealing
description: Learning rate scheduling with cosine annealing for smooth decay

# Model configuration
model:
  name: digit82/kobart-summarization
  architecture: kobart

# Tokenizer configuration  
tokenizer:
  encoder_max_len: 512
  decoder_max_len: 200
  bos_token: "<s>"
  eos_token: "</s>"
  special_tokens:
    - '#Person1#'
    - '#Person2#'
    - '#Person3#'
    - '#PhoneNumber#'
    - '#Address#'
    - '#DateOfBirth#'
    - '#PassportNumber#'
    - '#SSN#'
    - '#CardNumber#'
    - '#CarNumber#'
    - '#Email#'

# Training configuration with cosine annealing
training:
  num_train_epochs: 5  # Quick experiment
  learning_rate: 3.0e-05  # Slightly higher initial LR for cosine
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  fp16: true
  
  # Cosine annealing specific settings
  lr_scheduler_type: "cosine"  # Cosine annealing scheduler
  warmup_ratio: 0.1  # 10% warmup
  
  # Standard settings
  weight_decay: 0.01
  seed: 42
  evaluation_strategy: epoch
  save_strategy: epoch
  save_total_limit: 1
  logging_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: "eval_rouge_combined_f1"
  greater_is_better: true
  
  # Early stopping
  early_stopping_patience: 2
  early_stopping_threshold: 0.001
  
  # Other settings
  dataloader_num_workers: 4
  dataloader_drop_last: false
  group_by_length: true
  predict_with_generate: true
  remove_unused_columns: true

# Generation configuration
generation:
  max_length: 200
  num_beams: 4
  no_repeat_ngram_size: 2
  early_stopping: true
  length_penalty: 1.0

# Inference configuration
inference:
  batch_size: 16
  generate_max_length: 200
  remove_tokens:
    - '<usr>'
    - '<s>'
    - '</s>'
    - '<pad>'

# WandB configuration
wandb:
  name: "03a_lr_cosine_annealing"
  notes: "LR scheduling experiment with cosine annealing"
  tags: ["lr_scheduling", "cosine_annealing", "optimization", "kobart"]
  
# Data configuration
data:
  train_file: "train.csv"
  dev_file: "dev.csv"
  test_file: "test.csv"

# Logging configuration
logging:
  log_lr: true  # Log learning rate changes
  log_lr_every_step: false  # Log at each evaluation step instead
