# mT5 XL-Sum RTX 3090 극한 최적화 실험 (세계 대회 도전)
experiment_name: mt5_xlsum_ultimate_rtx3090
description: "mT5 XL-Sum RTX 3090 세계 대회 수준 성능 도전 - 3단계 극한 최적화"

general:
  model_name: csebuetnlp/mT5_multilingual_XLSum
  data_path: data/
  train_path: data/train.csv
  val_path: data/dev.csv
  model_type: seq2seq
  name: mt5_xlsum_ultimate_rtx3090

model:
  architecture: mt5
  checkpoint: csebuetnlp/mT5_multilingual_XLSum

# 🏆 세계 대회 수준 prefix
input_prefix: "dialogue summarization in korean: "

tokenizer:
  bos_token: <pad>
  eos_token: </s>
  encoder_max_len: 1024              # RTX 3090 최대 컨텍스트
  decoder_max_len: 200
  special_tokens:
    - '#Person1#'
    - '#Person2#'
    - '#Person3#'
    - '#PhoneNumber#'
    - '#Address#'
    - '#PassportNumber#'
    - '#DateOfBirth#'
    - '#SSN#'
    - '#CardNumber#'
    - '#CarNumber#'
    - '#Email#'
    - '<summary>'
    - '</summary>'
    - '<dialogue>'
    - '</dialogue>'

# 🚀 RTX 3090 극한 최적화 (세계 대회 수준)
training:
  do_eval: true
  do_train: true
  evaluation_strategy: steps
  eval_steps: 100
  
  # 🔥 RTX 3090 최대 성능 활용
  per_device_train_batch_size: 4      # 긴 시퀀스(1024) 고려
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4      # 유효 배치 16
  
  # ⚡ 극한 학습률 (세계 대회 수준)
  num_train_epochs: 8                 # 충분한 학습
  learning_rate: 1.2e-04              # 극한 학습률 (RTX 3090 안정선)
  lr_scheduler_type: cosine_with_restarts
  warmup_ratio: 0.02
  weight_decay: 0.0001
  
  # 🎯 RTX 3090 최고 정밀도
  fp16: false
  bf16: true                          # 최고 안정성
  gradient_checkpointing: false
  dataloader_num_workers: 12          # RTX 3090 최대 활용
  dataloader_pin_memory: true
  group_by_length: true
  
  # 📊 극세밀 모니터링
  logging_steps: 10
  save_strategy: steps
  save_steps: 100
  save_total_limit: 12
  load_best_model_at_end: true
  early_stopping_patience: 12
  
  # 🏆 세계 대회 수준 생성
  predict_with_generate: true
  generation_num_beams: 10            # RTX 3090에서 가능한 최대
  generation_max_length: 200
  generation_min_length: 20
  generation_length_penalty: 0.6
  generation_no_repeat_ngram_size: 4
  generation_do_sample: false
  
  report_to: wandb
  seed: 42

# 🚀 RTX 3090 극한 QLoRA (최대 표현력) (Unsloth 활성화)
qlora:
  use_unsloth: true
  use_qlora: true
  lora_rank: 96                       # RTX 3090 한계까지
  lora_alpha: 192                     # rank의 2배
  lora_dropout: 0.01                  # 최소 드롭아웃
  target_modules: ["q", "k", "v", "o", "wi", "wo", "lm_head", "embed_tokens"]
  load_in_4bit: true
  bnb_4bit_compute_dtype: "bfloat16"
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true

wandb:
  entity: lyjune37-juneictlab
  project: nlp-5
  name: mt5_xlsum_ultimate_rtx3090_challenge
  tags: [mT5, XL-Sum, RTX3090, ultimate, world_competition_level, stage3]
  notes: "mT5 XL-Sum RTX 3090 세계 대회 수준 도전 - 극한 최적화"

# Generation settings
generation:
  max_length: 256
  min_length: 5
  num_beams: 4
  no_repeat_ngram_size: 2
\ntraining:\n  eval_strategy: no
