general:
  data_path: ./data/
  model_name: digit82/kobart-summarization
  output_dir: ./outputs/exp_auto_0729125328
inference:
  batch_size: 16
  ckt_dir: ./outputs/exp_auto_0729125328/best
  early_stopping: true
  generate_max_length: 160
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - None
  - </s>
  - <pad>
  result_path: ./outputs/exp_auto_0729125328/submission_0729125328.csv
tokenizer:
  bos_token: None
  decoder_max_len: 160
  encoder_max_len: 1300
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#DateOfBirth#'
  - '#PassportNumber#'
  - '#SSN#'
  - '#CardNumber#'
  - '#CarNumber#'
  - '#Email#'
training:
  bf16: true
  dataloader_drop_last: false
  dataloader_num_workers: 8
  early_stopping_patience: 1
  early_stopping_threshold: 0.001
  eval_steps: 400
  evaluation_strategy: steps
  fp16: false
  generation_max_length: 160
  gradient_accumulation_steps: 2
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  group_by_length: true
  learning_rate: 1.0e-05
  load_best_model_at_end: true
  logging_dir: ./outputs/exp_auto_0729125328
  logging_steps: 400
  num_train_epochs: 1
  output_dir: ./outputs/exp_auto_0729125328
  overwrite_output_dir: false
  per_device_eval_batch_size: 16
  per_device_train_batch_size: 16
  predict_with_generate: true
  remove_unused_columns: true
  report_to: all
  save_steps: 400
  save_total_limit: 1
  seed: 42
  torch_empty_cache_steps: 2
  warmup_steps: 10
  weight_decay: 0.001
wandb:
  entity: skiersong
  name: baseline_test_0729125328
  notes: Baseline-test
  project: nlp-5
