experiment_name: batch_optimization_large_no_accum
description: Large batch size with no gradient accumulation (effective batch=64)

# 모델 구성
model:
  name: digit82/kobart-summarization
  architecture: kobart

# 토크나이저 구성  
tokenizer:
  encoder_max_len: 512
  decoder_max_len: 200
  bos_token: "<s>"
  eos_token: "</s>"
  special_tokens:
    - '#Person1#'
    - '#Person2#'
    - '#Person3#'
    - '#PhoneNumber#'
    - '#Address#'
    - '#DateOfBirth#'
    - '#PassportNumber#'
    - '#SSN#'
    - '#CardNumber#'
    - '#CarNumber#'
    - '#Email#'

# 학습 구성 - 큰 배치, accumulation 없음
training:
  num_train_epochs: 5  # 빠른 실험
  learning_rate: 1.0e-05
  
  # 배치 설정: 큰 배치 크기 + accumulation 없음
  per_device_train_batch_size: 64   # 큰 배치 크기 (메모리 사용 최대)
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1    # accumulation 없음 (효과적인 배치 크기 = 64)
  
  # 메모리 최적화
  gradient_checkpointing: false     # 큰 배치에서는 필요 없을 수 있음
  fp16: true                       # Mixed precision 필수
  optim: "adamw_torch"            # 표준 optimizer
  
  # 표준 설정
  warmup_steps: 100
  weight_decay: 0.01
  seed: 42
  evaluation_strategy: epoch
  save_strategy: epoch
  save_total_limit: 1
  logging_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: "eval_rouge_combined_f1"
  greater_is_better: true
  
  # 조기 종료
  early_stopping_patience: 2
  early_stopping_threshold: 0.001
  
  # 데이터로더 설정
  dataloader_num_workers: 8  # 더 많은 워커로 데이터 로딩 속도 향상
  dataloader_drop_last: false
  group_by_length: true
  predict_with_generate: true
  remove_unused_columns: true
  
  # 메모리 관리
  torch_empty_cache_steps: 50  # 더 자주 캐시 비우기 (큰 배치 때문에)

# 생성 구성
generation:
  max_length: 200
  num_beams: 4
  no_repeat_ngram_size: 2
  early_stopping: true
  length_penalty: 1.0

# 추론 구성
inference:
  batch_size: 64  # 큰 배치 크기
  generate_max_length: 200
  remove_tokens:
    - '<usr>'
    - '<s>'
    - '</s>'
    - '<pad>'

# WandB 구성
wandb:
  name: "05c_batch_large_no_accum"
  notes: "Batch optimization: large batch (64) + no accumulation (1) = effective 64"
  tags: ["batch_optimization", "large_batch", "no_accumulation", "kobart"]
  
# 데이터 구성
data:
  train_file: "train.csv"
  dev_file: "dev.csv"
  test_file: "test.csv"

# 성능 모니터링
monitoring:
  log_memory_usage: true
  log_training_speed: true
  log_gpu_stats: true
