# NLP 대화 요약 프로젝트 - 하이퍼파라미터 자동 튜닝 설정
# 6조 방식의 베이지안 최적화를 NLP에 적용

project: nlp-summarization-auto
entity: wandb_repo
program: sweep_runner.py

# 최적화 방법: 베이지안 최적화 (6조와 동일)
method: bayes

# 최적화 목표: Multi-reference ROUGE 점수 합계
metric:
  name: rouge_combined_f1  # ROUGE-1 + ROUGE-2 + ROUGE-L 합계
  goal: maximize

# 조기 종료 설정 (리소스 절약)
early_terminate:
  type: hyperband
  min_iter: 3
  max_iter: 20
  s: 2

# 하이퍼파라미터 탐색 공간 정의
parameters:
  # 학습률 관련 (로그 균등 분포)
  learning_rate:
    distribution: log_uniform_values
    min: 1.0e-6
    max: 1.0e-4
  
  # 배치 크기 (GPU 메모리 고려)
  per_device_train_batch_size:
    values: [8, 16, 32, 64]
  
  per_device_eval_batch_size:
    values: [16, 32, 64]
  
  # 토큰 길이 설정 (NLP 특화)
  encoder_max_len:
    values: [256, 512, 1024]
  
  decoder_max_len:
    values: [64, 100, 128, 256]
  
  # 정규화 파라미터
  weight_decay:
    distribution: log_uniform_values
    min: 1.0e-3
    max: 1.0e-1
  
  warmup_ratio:
    values: [0.0, 0.1, 0.2, 0.3]
  
  # 생성 파라미터 (NLP 특화)
  num_beams:
    values: [3, 4, 5, 8]
  
  no_repeat_ngram_size:
    values: [2, 3, 4]
  
  length_penalty:
    distribution: uniform
    min: 0.8
    max: 1.5
  
  # 학습 에폭 및 스케줄링
  num_train_epochs:
    values: [10, 15, 20, 25]
  
  lr_scheduler_type:
    values: ['cosine', 'linear', 'cosine_with_restarts']
  
  # 배치 누적 (메모리 제약 대응)
  gradient_accumulation_steps:
    values: [1, 2, 4]
  
  # 정규화 기법
  label_smoothing:
    values: [0.0, 0.1, 0.2]
  
  # 조기 종료
  early_stopping_patience:
    values: [3, 5, 7]
  
  # 생성 길이
  generation_max_length:
    values: [80, 100, 120, 150]
  
  # 옵티마이저 설정
  optim:
    values: ['adamw_torch', 'adamw_hf', 'adafactor']

# 실험 제약 조건 (메모리 최적화)
# 긴 시퀀스 사용 시 배치 크기 제한
constraints:
  - name: memory_constraint_1
    condition: encoder_max_len > 512
    then:
      per_device_train_batch_size:
        max: 16
  
  - name: memory_constraint_2  
    condition: encoder_max_len > 1024
    then:
      per_device_train_batch_size:
        max: 8
      gradient_accumulation_steps:
        min: 2

# 실험 메타데이터
run_cap: 50  # 최대 실험 횟수
description: "NLP Dialogue Summarization Hyperparameter Optimization using Bayesian Optimization"
