experiment_name: lr_scheduling_inverse_sqrt
description: Inverse square root decay - popular for transformer models

# Model configuration
model:
  name: digit82/kobart-summarization
  architecture: kobart

# Tokenizer configuration  
tokenizer:
  encoder_max_len: 512
  decoder_max_len: 200
  bos_token: "<s>"
  eos_token: "</s>"
  special_tokens:
    - '#Person1#'
    - '#Person2#'
    - '#Person3#'
    - '#PhoneNumber#'
    - '#Address#'
    - '#DateOfBirth#'
    - '#PassportNumber#'
    - '#SSN#'
    - '#CardNumber#'
    - '#CarNumber#'
    - '#Email#'

# Training configuration with inverse sqrt decay
training:
  num_train_epochs: 5  # Quick experiment
  learning_rate: 2.0e-05  # Initial LR
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  fp16: true
  
  # Inverse sqrt decay (approximated with polynomial)
  lr_scheduler_type: "polynomial"
  warmup_steps: 400  # Warmup steps
  lr_scheduler_kwargs:
    power: 0.5  # Square root decay (1/sqrt(t))
    lr_end: 1.0e-06
  
  # Standard settings
  weight_decay: 0.01
  seed: 42
  evaluation_strategy: epoch
  save_strategy: epoch
  save_total_limit: 1
  logging_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: "eval_rouge_combined_f1"
  greater_is_better: true
  
  # Early stopping
  early_stopping_patience: 2
  early_stopping_threshold: 0.001
  
  # Other settings
  dataloader_num_workers: 4
  dataloader_drop_last: false
  group_by_length: true
  predict_with_generate: true
  remove_unused_columns: true

# Generation configuration
generation:
  max_length: 200
  num_beams: 4
  no_repeat_ngram_size: 2
  early_stopping: true
  length_penalty: 1.0

# Inference configuration
inference:
  batch_size: 16
  generate_max_length: 200
  remove_tokens:
    - '<usr>'
    - '<s>'
    - '</s>'
    - '<pad>'

# WandB configuration
wandb:
  name: "03f_lr_inverse_sqrt"
  notes: "LR scheduling with inverse square root decay (Transformer-style)"
  tags: ["lr_scheduling", "inverse_sqrt", "transformer_style", "optimization", "kobart"]
  
# Data configuration
data:
  train_file: "train.csv"
  dev_file: "dev.csv"
  test_file: "test.csv"

# Logging configuration
logging:
  log_lr: true
  log_lr_every_step: false
